### PR TITLE
Use preprocess2

### PR DESCRIPTION
**Pull request by jelovirt**
## Description
Use preprocess2.

## Motivation and Context
Move to map-first preprocessing.

### CODE REVIEW

**Comment by infotexture** [comment]
See https://github.com/dita-ot/website/pull/796 for test diffs generated by this plug-in branch.

Here are a few things I noticed:

- ✅ **In related links output, relative paths are simplified**: where previous versions generated links that went up and back down, like `../parent/current-topic-sibling.html`, this version writes `current-topic-sibling.html`. 
- ❌ **In related links output, `<dvrResourcePrefix>` from [publishing.ditamap#L15](https://github.com/dita-ot/docs/blob/develop/topics/publishing.ditamap#L15) is not applied.** The link is generated using the unprefixed filename.
- Subject scheme processing is stricter, reporting errors that are not emitted in `preprocess`:

      [DOTJ049W][WARN] The @outputclass attribute value 'markdown' on the <codeblock> element 
      does not comply with the specified subject scheme. According to the subject scheme map, 
      the following values are valid for the @outputclass attribute: 'language-haskell,multi-
      platform,syntax-batch,language-markup,language-mathml,language-markdown,language-html,
      language-clike,language-javascript,language-bash,show-whitespace,language-java,language-svg,
      language-css,language-dockerfile,language-yaml,syntax-bash,show-line-numbers,language-json,
      normalize-space,language-properties,language-xml'.

**Comment by jelovirt** [comment]
The `DOTJ049W` warning seems right. I don't know why old preprocess didn't report these, but to me it's the correct behviour.

**Comment by jelovirt** [comment]
> …relative paths are simplified

This is an improvement, I don't see this a bug.

**Comment by jelovirt** [comment]
> In related links output, `<dvrResourcePrefix>`… is not applied

I extracted only the equivalent branch filter and it's working. @infotexture are you able to create a small example set where the `<dvrResourcePrefix>` doesn't work?

**Comment by infotexture** [comment]
> are you able to create a small example set where the `<dvrResourcePrefix>` doesn't work?

@jelovirt See line diff in updated https://github.com/dita-ot/org.dita-ot.html/pull/13#issuecomment-1913332262 above.

**Comment by infotexture** [comment]
✅ The `<dvrResourcePrefix>` issue is resolved with https://github.com/dita-ot/dita-ot/pull/4369.

(Updated https://github.com/dita-ot/org.dita-ot.html/pull/13#issuecomment-1913332262 above).

**Pull request merged**
